apiVersion: v1
kind: Template
metadata:
  name: freqtrade
  annotations:
    description: freqtrade
    tags: btc, exchange
objects:
# Deployment Configuration
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 302
    labels:
      app: freqtrade
      stage: prod
      version: ${FREQTRADE_VERSION}
    name: freqtrade-btc
  spec:
    replicas: 1
    strategy:
      type: Rolling
      rollingParams:
        intervalSeconds: 20
        maxUnavailable: 0%
        timeoutSeconds: 600
        maxSurge: 25%
    selector:
      app: freqtrade-btc
      deploymentconfig: freqtrade-btc
    template:
      metadata:
        labels:
          app: freqtrade-btc
          deploymentconfig: freqtrade-btc
      spec:
        containers:
          - env:
              - name: STAGE
                value: ${STAGE}
            image: fthievent/freqtrade
            imagePullPolicy: Always
            name: freqtrade-btc
            ports:
              - containerPort: 3000
                protocol: TCP
            resources:
              limits:
                cpu: 4
                memory: 8Gi
              requests:
                cpu: 1
                memory: 2Gi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
# Parameters/ Environment
parameters:
  - name: STAGE
    description: "The stage: dev, inte, prod"
    required: false
    value: prod
  - name: FREQTRADE_VERSION
    description: "Version"
    required: false
    value: "1.0"
  - name: STRATEGY
    description: "Strategy to use"
    value: Strategy002
    required: true