apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: '2020-05-25T12:39:48Z'
  generation: 8
  labels:
    app: freqtrade-opt
    stage: opt
    version: '1.0'
  name: freqtrade-opt
  namespace: freqtrade
  resourceVersion: '32118'
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/freqtrade/deploymentconfigs/freqtrade-opt
  uid: d1df7e86-9e84-11ea-a09a-001c42aed741
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: freqtrade-opt
    deploymentconfig: freqtrade-opt
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: freqtrade-opt
        deploymentconfig: freqtrade-opt
    spec:
      containers:
        - env:
            - name: STRATEGY
              value: Quickie
            - name: CONFIG_FILE
              value: /freqtrade/user_data/config-opt.json
            - name: LOG_FILE
              value: /freqtrade/user_data/logs/freqtrade-opt.log
            - name: DB_URL
              value: 'sqlite:////freqtrade/user_data/tradesv3.opt.sqlite'
          image: fthievent/freqtrade
          imagePullPolicy: Always
          name: freqtrade-opt
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 8Gi
            requests:
              cpu: '1'
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /freqtrade/user_data
              name: freq-opt-data
              subPath: ./user_data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: freq-opt-data
          persistentVolumeClaim:
            claimName: freqtrade-opt-data
  test: false
  triggers:
    - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-05-25T13:20:14Z'
      lastUpdateTime: '2020-05-25T13:20:14Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-05-25T13:20:09Z'
      lastUpdateTime: '2020-05-25T13:20:15Z'
      message: replication controller "freqtrade-opt-7" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 7
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
